env: dev

log:
  level: debug

server:
  port: 50051
  host: 0.0.0.0

httpServer:
  port: 8080

prometheus:
  enabled: true
  host: 0.0.0.0
  port: 8000

img2vec:
  addr: localhost:50052

milvus:
  addr: localhost:19530
  vectorDim: 768
  metricType: L2
  nProbe: 19
  collectionName: products_revis_digikala_clip_ViT_L_14_336px

objectDetector:
  addr: localhost:50052

redis:
  addr: localhost:6379
