version: "3.7"

services:
  app:
    build: .
    ports:
      - "50051:50051"
      - "8080:8080"
    command:
      - "./dvs"
      - "serve"
      - "--config"
      - "/app/config.yml"
    volumes:
      - ./internal/cfg/config.dev.yml:/app/config.yml
