// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: favorite.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
	regexp "regexp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_AddItemToFavoritesRequest_ListName = regexp.MustCompile(`^favorites$`)

func (this *AddItemToFavoritesRequest) Validate() error {
	if !_regex_AddItemToFavoritesRequest_ListName.MatchString(this.ListName) {
		return github_com_mwitkow_go_proto_validators.FieldError("ListName", fmt.Errorf(`value '%v' must be a string conforming to regex "^favorites$"`, this.ListName))
	}
	if !(this.ProductId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProductId", fmt.Errorf(`value '%v' must be greater than '0'`, this.ProductId))
	}
	return nil
}
func (this *AddItemToFavoritesResponse) Validate() error {
	return nil
}

var _regex_RemoveItemFromFavoritesRequest_ListName = regexp.MustCompile(`^favorites$`)

func (this *RemoveItemFromFavoritesRequest) Validate() error {
	if !_regex_RemoveItemFromFavoritesRequest_ListName.MatchString(this.ListName) {
		return github_com_mwitkow_go_proto_validators.FieldError("ListName", fmt.Errorf(`value '%v' must be a string conforming to regex "^favorites$"`, this.ListName))
	}
	if !(this.ProductId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProductId", fmt.Errorf(`value '%v' must be greater than '0'`, this.ProductId))
	}
	return nil
}
func (this *RemoveItemFromFavoritesResponse) Validate() error {
	return nil
}

var _regex_GetFavoritesRequest_ListName = regexp.MustCompile(`^favorites$`)

func (this *GetFavoritesRequest) Validate() error {
	if !_regex_GetFavoritesRequest_ListName.MatchString(this.ListName) {
		return github_com_mwitkow_go_proto_validators.FieldError("ListName", fmt.Errorf(`value '%v' must be a string conforming to regex "^favorites$"`, this.ListName))
	}
	return nil
}
func (this *GetFavoritesResponse) Validate() error {
	for _, item := range this.Products {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Products", err)
			}
		}
	}
	return nil
}
