// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: img2vec.proto

package img2vec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_img2vec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_img2vec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_img2vec_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vector []float32 `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_img2vec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_img2vec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_img2vec_proto_rawDescGZIP(), []int{1}
}

func (x *Vector) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

var File_img2vec_proto protoreflect.FileDescriptor

var file_img2vec_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6d, 0x67, 0x32, 0x76, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x69, 0x6d, 0x67, 0x32, 0x76, 0x65, 0x63, 0x22, 0x1d, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x06, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x39, 0x0a, 0x07, 0x49, 0x6d, 0x67,
	0x32, 0x56, 0x65, 0x63, 0x12, 0x2e, 0x0a, 0x09, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x7a,
	0x65, 0x12, 0x0e, 0x2e, 0x69, 0x6d, 0x67, 0x32, 0x76, 0x65, 0x63, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x1a, 0x0f, 0x2e, 0x69, 0x6d, 0x67, 0x32, 0x76, 0x65, 0x63, 0x2e, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x69, 0x6d, 0x67, 0x32, 0x76,
	0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_img2vec_proto_rawDescOnce sync.Once
	file_img2vec_proto_rawDescData = file_img2vec_proto_rawDesc
)

func file_img2vec_proto_rawDescGZIP() []byte {
	file_img2vec_proto_rawDescOnce.Do(func() {
		file_img2vec_proto_rawDescData = protoimpl.X.CompressGZIP(file_img2vec_proto_rawDescData)
	})
	return file_img2vec_proto_rawDescData
}

var file_img2vec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_img2vec_proto_goTypes = []interface{}{
	(*Image)(nil),  // 0: img2vec.Image
	(*Vector)(nil), // 1: img2vec.Vector
}
var file_img2vec_proto_depIdxs = []int32{
	0, // 0: img2vec.Img2Vec.Vectorize:input_type -> img2vec.Image
	1, // 1: img2vec.Img2Vec.Vectorize:output_type -> img2vec.Vector
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_img2vec_proto_init() }
func file_img2vec_proto_init() {
	if File_img2vec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_img2vec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_img2vec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_img2vec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_img2vec_proto_goTypes,
		DependencyIndexes: file_img2vec_proto_depIdxs,
		MessageInfos:      file_img2vec_proto_msgTypes,
	}.Build()
	File_img2vec_proto = out.File
	file_img2vec_proto_rawDesc = nil
	file_img2vec_proto_goTypes = nil
	file_img2vec_proto_depIdxs = nil
}
